### PR TITLE
Fixed issue of archived observation causing new ones not to save

### PR DESCRIPTION
**Pull request by dikumheartland**

### CODE REVIEW

**Review by lilkersy — APPROVED** [review]
I understand that this is now trying to check and account for unarchived data before building observation(s) to save, yeah?

**Comment by dikumheartland** [comment]
> I understand that this is now trying to check and account for unarchived data before building observation(s) to save, yeah?

Yep

**Comment by Mathew77** [comment]
Hi @dikumheartland, I try to test from my end is not working I can't still save after deleting a care & support form.

**Comment by dikumheartland** [comment]
> Hi @dikumheartland, I try to test from my end is not working I can't still save after deleting a care & support form.
> 
> Check the ObservationService.java from line 50-55 check the if statement, you need to check for achieved.

Okay @Mathew77 We will check this. I'm surprised though because the repo isn't even fetching the archived observations for the client. I also tested this from my end.

**Comment by lilkersy** [comment]
Am I missing something? @dikumheartland were there changes made to the save functionality itself? Because I only see repository related code. Or do I not understand?

**Comment by dikumheartland** [comment]
> Am I missing something? @dikumheartland were there changes made to the save functionality itself? Because I only see repository related code. Or do I not understand?

The previous repo method - getAllByPersonAndFacilityId was used by from the front end to get existing observations for a client. Using this, it then checks if the date being saved is existing. This method also fetched archived records which caused issues. The new method ignores the archived observations.

**Pull request merged**
